# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: codeworm
description: a coderworm's footprint 
author:
  name: yuxing 
  email: yuxingfirst@gmail.com 
  github: yuxingfirst 
  twitter: 201281062
  pinterest: 
  linkedin: JerryX
  bio: a coderworm's footprint!
  email_md5: 4ac03b3603f6a91430c289a4ef23a32f 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://yuxingfirst.github.io/blog/

ORIGIN_PATH: https://raw.github.com/yuxingfirst/blog/gh-pages

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://coderworm.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
